# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subscriptions0_analytics_get200_response_stats import Subscriptions0AnalyticsGet200ResponseStats

class TestSubscriptions0AnalyticsGet200ResponseStats(unittest.TestCase):
    """Subscriptions0AnalyticsGet200ResponseStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Subscriptions0AnalyticsGet200ResponseStats:
        """Test Subscriptions0AnalyticsGet200ResponseStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Subscriptions0AnalyticsGet200ResponseStats`
        """
        model = Subscriptions0AnalyticsGet200ResponseStats()
        if include_optional:
            return Subscriptions0AnalyticsGet200ResponseStats(
                views = '',
                downloads = '',
                likes = '',
                collects = '',
                makes = ''
            )
        else:
            return Subscriptions0AnalyticsGet200ResponseStats(
        )
        """

    def testSubscriptions0AnalyticsGet200ResponseStats(self):
        """Test Subscriptions0AnalyticsGet200ResponseStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
