# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.image_summary_sizes_inner import ImageSummarySizesInner

class TestImageSummarySizesInner(unittest.TestCase):
    """ImageSummarySizesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageSummarySizesInner:
        """Test ImageSummarySizesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageSummarySizesInner`
        """
        model = ImageSummarySizesInner()
        if include_optional:
            return ImageSummarySizesInner(
                type = 'thumb',
                size = 'large',
                url = 'https://cdn.thingiverse.com/renders/62/ab/d7/e3/ea/1_3D-printed_3DBenchy_by_Creative-Tools.com_thumb_large.JPG'
            )
        else:
            return ImageSummarySizesInner(
        )
        """

    def testImageSummarySizesInner(self):
        """Test ImageSummarySizesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
