# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.changelog_api import ChangelogApi


class TestChangelogApi(unittest.TestCase):
    """ChangelogApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChangelogApi()

    def tearDown(self) -> None:
        pass

    def test_changelogs_get(self) -> None:
        """Test case for changelogs_get

        Get changelogs
        """
        pass


if __name__ == '__main__':
    unittest.main()
