# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.group_api import GroupApi


class TestGroupApi(unittest.TestCase):
    """GroupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupApi()

    def tearDown(self) -> None:
        pass

    def test_groups_get(self) -> None:
        """Test case for groups_get

        List of groups
        """
        pass

    def test_groups_group_id_delete(self) -> None:
        """Test case for groups_group_id_delete

        Delete a group
        """
        pass

    def test_groups_group_id_forum_by_slug_forum_slug_get(self) -> None:
        """Test case for groups_group_id_forum_by_slug_forum_slug_get

        Get group forum by slug
        """
        pass

    def test_groups_group_id_forum_forum_id_delete(self) -> None:
        """Test case for groups_group_id_forum_forum_id_delete

        Delete group forum
        """
        pass

    def test_groups_group_id_forum_topics_forum_id_get(self) -> None:
        """Test case for groups_group_id_forum_topics_forum_id_get

        Get all topics for the group forum
        """
        pass

    def test_groups_group_id_get(self) -> None:
        """Test case for groups_group_id_get

        Get group by id
        """
        pass

    def test_groups_group_id_group_forums_get(self) -> None:
        """Test case for groups_group_id_group_forums_get

        List of group forums
        """
        pass

    def test_groups_group_id_group_forums_post(self) -> None:
        """Test case for groups_group_id_group_forums_post

        Create a new forum
        """
        pass

    def test_groups_group_id_group_topics_forum_slug_post(self) -> None:
        """Test case for groups_group_id_group_topics_forum_slug_post

        Create a new Group Topic
        """
        pass

    def test_groups_group_id_group_topics_get(self) -> None:
        """Test case for groups_group_id_group_topics_get

        List of group topics
        """
        pass

    def test_groups_group_id_image_post(self) -> None:
        """Test case for groups_group_id_image_post

        Upload a new image of group
        """
        pass

    def test_groups_group_id_members_delete(self) -> None:
        """Test case for groups_group_id_members_delete

        Leave group
        """
        pass

    def test_groups_group_id_members_get(self) -> None:
        """Test case for groups_group_id_members_get

        List of group members
        """
        pass

    def test_groups_group_id_members_post(self) -> None:
        """Test case for groups_group_id_members_post

        Join to group
        """
        pass

    def test_groups_group_id_patch(self) -> None:
        """Test case for groups_group_id_patch

        Update an existing group
        """
        pass

    def test_groups_group_id_things_get(self) -> None:
        """Test case for groups_group_id_things_get

        List of group things
        """
        pass

    def test_groups_group_id_things_thing_id_delete(self) -> None:
        """Test case for groups_group_id_things_thing_id_delete

        Delete thing from group
        """
        pass

    def test_groups_group_id_things_thing_id_post(self) -> None:
        """Test case for groups_group_id_things_thing_id_post

        Add thing to group
        """
        pass

    def test_groups_group_id_update_group_forum_forum_id_post(self) -> None:
        """Test case for groups_group_id_update_group_forum_forum_id_post

        Update a certain forum of group
        """
        pass

    def test_groups_post(self) -> None:
        """Test case for groups_post

        Create a new group
        """
        pass


if __name__ == '__main__':
    unittest.main()
