# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.home_banner_api import HomeBannerApi


class TestHomeBannerApi(unittest.TestCase):
    """HomeBannerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HomeBannerApi()

    def tearDown(self) -> None:
        pass

    def test_homebanner_get(self) -> None:
        """Test case for homebanner_get

        Get the banner on the home page
        """
        pass


if __name__ == '__main__':
    unittest.main()
