# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.app_api import AppApi


class TestAppApi(unittest.TestCase):
    """AppApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppApi()

    def tearDown(self) -> None:
        pass

    def test_apps0_approvedandpublished_get(self) -> None:
        """Test case for apps0_approvedandpublished_get

        Get all approved and published apps
        """
        pass

    def test_apps_id_get(self) -> None:
        """Test case for apps_id_get

        Get app by id
        """
        pass


if __name__ == '__main__':
    unittest.main()
