# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.categories_slug_get200_response import CategoriesSlugGet200Response

class TestCategoriesSlugGet200Response(unittest.TestCase):
    """CategoriesSlugGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CategoriesSlugGet200Response:
        """Test CategoriesSlugGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CategoriesSlugGet200Response`
        """
        model = CategoriesSlugGet200Response()
        if include_optional:
            return CategoriesSlugGet200Response(
                name = '',
                url = '',
                count = 56,
                things_url = '',
                thumbnail = '',
                preview_image = '',
                children = [
                    openapi_client.models.category_schema.category_schema(
                        id = 56, 
                        name = '', 
                        url = '', 
                        count = 56, 
                        slug = '', 
                        things_url = '', )
                    ]
            )
        else:
            return CategoriesSlugGet200Response(
        )
        """

    def testCategoriesSlugGet200Response(self):
        """Test CategoriesSlugGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
