# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.subscription_api import SubscriptionApi


class TestSubscriptionApi(unittest.TestCase):
    """SubscriptionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionApi()

    def tearDown(self) -> None:
        pass

    def test_events0_read_all_post(self) -> None:
        """Test case for events0_read_all_post

        Read all subscription-events of user
        """
        pass

    def test_events_id_delete(self) -> None:
        """Test case for events_id_delete

        Delete event by id
        """
        pass

    def test_subscriptions0_analytics_get(self) -> None:
        """Test case for subscriptions0_analytics_get

        Get activity analytics from the last 30 Days of a certain user
        """
        pass

    def test_subscriptions0_dashboard_get(self) -> None:
        """Test case for subscriptions0_dashboard_get

        Get activities of User in Dashboard page
        """
        pass

    def test_subscriptions0_dashboard_sources_get(self) -> None:
        """Test case for subscriptions0_dashboard_sources_get

        Get activity sources for editing the dashboard feed
        """
        pass

    def test_subscriptions_tag_is_user_subscribed_to_tag_get(self) -> None:
        """Test case for subscriptions_tag_is_user_subscribed_to_tag_get

        Check if user is subscribed to the tag
        """
        pass

    def test_subscriptions_tag_set_subscribe_state_post(self) -> None:
        """Test case for subscriptions_tag_set_subscribe_state_post

        Subscribe a user to a tag
        """
        pass


if __name__ == '__main__':
    unittest.main()
