# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_users_username_all_collected_things_get(self) -> None:
        """Test case for users_username_all_collected_things_get

        Get latest downloaded things by user
        """
        pass

    def test_users_username_avatar_image_post(self) -> None:
        """Test case for users_username_avatar_image_post

        Update the avatar image
        """
        pass

    def test_users_username_collections_get(self) -> None:
        """Test case for users_username_collections_get

        Get latest copies by user
        """
        pass

    def test_users_username_copies_get(self) -> None:
        """Test case for users_username_copies_get

        Get latest copies by user
        """
        pass

    def test_users_username_cover_image_post(self) -> None:
        """Test case for users_username_cover_image_post

        Update the cover image
        """
        pass

    def test_users_username_delete(self) -> None:
        """Test case for users_username_delete

        Soft delete a user's account
        """
        pass

    def test_users_username_downloads_get(self) -> None:
        """Test case for users_username_downloads_get

        Get latest downloaded things by user
        """
        pass

    def test_users_username_event_count_get(self) -> None:
        """Test case for users_username_event_count_get

        Get the count of events for user since the timestamp sent
        """
        pass

    def test_users_username_favorites_get(self) -> None:
        """Test case for users_username_favorites_get

        Get favorites by user
        """
        pass

    def test_users_username_followers_delete(self) -> None:
        """Test case for users_username_followers_delete

        Unfollow an user
        """
        pass

    def test_users_username_followers_get(self) -> None:
        """Test case for users_username_followers_get

        Get followers
        """
        pass

    def test_users_username_followers_post(self) -> None:
        """Test case for users_username_followers_post

        Follow an user
        """
        pass

    def test_users_username_following_get(self) -> None:
        """Test case for users_username_following_get

        Get array of users that requested user is following
        """
        pass

    def test_users_username_get(self) -> None:
        """Test case for users_username_get

        Get the specified user
        """
        pass

    def test_users_username_likes_get(self) -> None:
        """Test case for users_username_likes_get

        Get things liked by user
        """
        pass

    def test_users_username_likesids_get(self) -> None:
        """Test case for users_username_likesids_get

        Get all things id's like by user
        """
        pass

    def test_users_username_patch(self) -> None:
        """Test case for users_username_patch

        Update the user's profile
        """
        pass

    def test_users_username_recommended_tags_get(self) -> None:
        """Test case for users_username_recommended_tags_get

        Get the list of personal tags.
        """
        pass

    def test_users_username_recommended_things_get(self) -> None:
        """Test case for users_username_recommended_things_get

        Get a bunch random things from categories based on the users likes and collected things
        """
        pass

    def test_users_username_search_term_get(self) -> None:
        """Test case for users_username_search_term_get

        Search data by user
        """
        pass

    def test_users_username_stats_by_day_start_date_end_date_get(self) -> None:
        """Test case for users_username_stats_by_day_start_date_end_date_get

        Get user's analytics of viewing and downloading things per day
        """
        pass

    def test_users_username_stats_by_thing_start_date_end_date_get(self) -> None:
        """Test case for users_username_stats_by_thing_start_date_end_date_get

        Get user's analytics of viewing and downloading by things
        """
        pass

    def test_users_username_things_get(self) -> None:
        """Test case for users_username_things_get

        Get things by user
        """
        pass

    def test_users_username_unread_message_count_get(self) -> None:
        """Test case for users_username_unread_message_count_get

        Get the count of messages for user
        """
        pass


if __name__ == '__main__':
    unittest.main()
