# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.group_topic_api import GroupTopicApi


class TestGroupTopicApi(unittest.TestCase):
    """GroupTopicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupTopicApi()

    def tearDown(self) -> None:
        pass

    def test_grouptopics_grouptopic_id_comments_get(self) -> None:
        """Test case for grouptopics_grouptopic_id_comments_get

        Get all comments for this topic in a quick pre-threaded view
        """
        pass

    def test_grouptopics_grouptopic_id_comments_post(self) -> None:
        """Test case for grouptopics_grouptopic_id_comments_post

        Post a comment
        """
        pass

    def test_grouptopics_grouptopic_id_delete(self) -> None:
        """Test case for grouptopics_grouptopic_id_delete

        Delete Group Topic by id
        """
        pass

    def test_grouptopics_grouptopic_id_forumtopics_comments_get(self) -> None:
        """Test case for grouptopics_grouptopic_id_forumtopics_comments_get

        Get list topics and comments of a certain forum
        """
        pass

    def test_grouptopics_grouptopic_id_get(self) -> None:
        """Test case for grouptopics_grouptopic_id_get

        Get a group topic by id
        """
        pass

    def test_grouptopics_grouptopic_id_patch(self) -> None:
        """Test case for grouptopics_grouptopic_id_patch

        Update a group topic
        """
        pass

    def test_grouptopics_grouptopic_id_pin_delete(self) -> None:
        """Test case for grouptopics_grouptopic_id_pin_delete

        Unpin the group topic
        """
        pass

    def test_grouptopics_grouptopic_id_pin_post(self) -> None:
        """Test case for grouptopics_grouptopic_id_pin_post

        Pin the group topic
        """
        pass

    def test_grouptopics_grouptopic_id_root_comments_get(self) -> None:
        """Test case for grouptopics_grouptopic_id_root_comments_get

        Get an unthreaded paginated list of root comment objects
        """
        pass

    def test_grouptopics_grouptopic_id_update_post(self) -> None:
        """Test case for grouptopics_grouptopic_id_update_post

        Update GroupTopic
        """
        pass

    def test_grouptopics_grouptopic_id_watch_delete(self) -> None:
        """Test case for grouptopics_grouptopic_id_watch_delete

        Unwatch the group topic
        """
        pass

    def test_grouptopics_grouptopic_id_watch_post(self) -> None:
        """Test case for grouptopics_grouptopic_id_watch_post

        Watch the group topic
        """
        pass


if __name__ == '__main__':
    unittest.main()
