# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.group_topic_tags import GroupTopicTags

class TestGroupTopicTags(unittest.TestCase):
    """GroupTopicTags unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupTopicTags:
        """Test GroupTopicTags
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupTopicTags`
        """
        model = GroupTopicTags()
        if include_optional:
            return GroupTopicTags(
                name = '',
                url = openapi_client.models.url_schema.url_schema(
                    auth = '', 
                    hash = '', 
                    host = '', 
                    hostname = '', 
                    href = '', 
                    path = '', 
                    pathname = '', 
                    protocol = '', 
                    search = '', 
                    slashes = True, 
                    port = null, 
                    query = null, ),
                count = 56,
                absolute_url = ''
            )
        else:
            return GroupTopicTags(
        )
        """

    def testGroupTopicTags(self):
        """Test GroupTopicTags"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
