# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.thingops_ids_move_post200_response import ThingopsIdsMovePost200Response

class TestThingopsIdsMovePost200Response(unittest.TestCase):
    """ThingopsIdsMovePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThingopsIdsMovePost200Response:
        """Test ThingopsIdsMovePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThingopsIdsMovePost200Response`
        """
        model = ThingopsIdsMovePost200Response()
        if include_optional:
            return ThingopsIdsMovePost200Response(
                ids = [
                    56
                    ]
            )
        else:
            return ThingopsIdsMovePost200Response(
        )
        """

    def testThingopsIdsMovePost200Response(self):
        """Test ThingopsIdsMovePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
