# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.banner_api import BannerApi


class TestBannerApi(unittest.TestCase):
    """BannerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BannerApi()

    def tearDown(self) -> None:
        pass

    def test_banner0_page_ad_get(self) -> None:
        """Test case for banner0_page_ad_get

        Get banner (ad) for a certain page
        """
        pass

    def test_banner_get(self) -> None:
        """Test case for banner_get

        Get a banner (ad)
        """
        pass


if __name__ == '__main__':
    unittest.main()
