# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.users_username_event_count_get200_response import UsersUsernameEventCountGet200Response

class TestUsersUsernameEventCountGet200Response(unittest.TestCase):
    """UsersUsernameEventCountGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsersUsernameEventCountGet200Response:
        """Test UsersUsernameEventCountGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsersUsernameEventCountGet200Response`
        """
        model = UsersUsernameEventCountGet200Response()
        if include_optional:
            return UsersUsernameEventCountGet200Response(
                count = 10
            )
        else:
            return UsersUsernameEventCountGet200Response(
        )
        """

    def testUsersUsernameEventCountGet200Response(self):
        """Test UsersUsernameEventCountGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
