# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.deprecated_api import DeprecatedApi


class TestDeprecatedApi(unittest.TestCase):
    """DeprecatedApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeprecatedApi()

    def tearDown(self) -> None:
        pass

    def test_featured_get(self) -> None:
        """Test case for featured_get

        Get the list of featured things
        """
        pass

    def test_files0_finalize_files_post(self) -> None:
        """Test case for files0_finalize_files_post

        Finalize multiple uploaded files. DEPRECATED, use FinalizeFiles endpoint instead
        """
        pass

    def test_files_file_id_finalize_get(self) -> None:
        """Test case for files_file_id_finalize_get

        Finalize an uploaded file. DEPRECATED.
        """
        pass

    def test_files_file_id_finalize_post(self) -> None:
        """Test case for files_file_id_finalize_post

        Finalize an uploaded file. DEPRECATED, use FinalizeFiles endpoint instead
        """
        pass

    def test_newest_get(self) -> None:
        """Test case for newest_get

        Get a list of the latest things
        """
        pass

    def test_popular_get(self) -> None:
        """Test case for popular_get

        Get the most popular things
        """
        pass


if __name__ == '__main__':
    unittest.main()
