# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.things_post403_response import ThingsPost403Response

class TestThingsPost403Response(unittest.TestCase):
    """ThingsPost403Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThingsPost403Response:
        """Test ThingsPost403Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThingsPost403Response`
        """
        model = ThingsPost403Response()
        if include_optional:
            return ThingsPost403Response(
                error = 'Forbidden'
            )
        else:
            return ThingsPost403Response(
        )
        """

    def testThingsPost403Response(self):
        """Test ThingsPost403Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
