# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.category_schema import CategorySchema

class TestCategorySchema(unittest.TestCase):
    """CategorySchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CategorySchema:
        """Test CategorySchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CategorySchema`
        """
        model = CategorySchema()
        if include_optional:
            return CategorySchema(
                id = 56,
                name = '',
                url = '',
                count = 56,
                slug = '',
                things_url = ''
            )
        else:
            return CategorySchema(
        )
        """

    def testCategorySchema(self):
        """Test CategorySchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
