# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.thing_api import ThingApi


class TestThingApi(unittest.TestCase):
    """ThingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ThingApi()

    def tearDown(self) -> None:
        pass

    def test_things0_random_get(self) -> None:
        """Test case for things0_random_get

        Get 5 random things with minimal 1000 likes
        """
        pass

    def test_things_post(self) -> None:
        """Test case for things_post

        Create a new thing
        """
        pass

    def test_things_thing_id_ancestors_get(self) -> None:
        """Test case for things_thing_id_ancestors_get

        Get a list of thing ancestors
        """
        pass

    def test_things_thing_id_categories_get(self) -> None:
        """Test case for things_thing_id_categories_get

        Get thing category
        """
        pass

    def test_things_thing_id_collections_delete(self) -> None:
        """Test case for things_thing_id_collections_delete

        Delete a thing from all user's collections
        """
        pass

    def test_things_thing_id_comments_get(self) -> None:
        """Test case for things_thing_id_comments_get

        Get an unthreaded paginated list of comment objects
        """
        pass

    def test_things_thing_id_comments_post(self) -> None:
        """Test case for things_thing_id_comments_post

        Post a comment
        """
        pass

    def test_things_thing_id_copies_get(self) -> None:
        """Test case for things_thing_id_copies_get

        Get copies/makes of a thing
        """
        pass

    def test_things_thing_id_copies_post(self) -> None:
        """Test case for things_thing_id_copies_post

        Upload image for new copy
        """
        pass

    def test_things_thing_id_delete(self) -> None:
        """Test case for things_thing_id_delete

        Delete a thing
        """
        pass

    def test_things_thing_id_derivatives_get(self) -> None:
        """Test case for things_thing_id_derivatives_get

        Get a list of thing derivatives
        """
        pass

    def test_things_thing_id_files_file_id_delete(self) -> None:
        """Test case for things_thing_id_files_file_id_delete

        Delete a file from a thing
        """
        pass

    def test_things_thing_id_files_file_id_get(self) -> None:
        """Test case for things_thing_id_files_file_id_get

        Get file by thing
        """
        pass

    def test_things_thing_id_files_get(self) -> None:
        """Test case for things_thing_id_files_get

        Get files by thing
        """
        pass

    def test_things_thing_id_get(self) -> None:
        """Test case for things_thing_id_get

        Get thing by id
        """
        pass

    def test_things_thing_id_images_get(self) -> None:
        """Test case for things_thing_id_images_get

        Get image(s) by thing
        """
        pass

    def test_things_thing_id_images_image_id_delete(self) -> None:
        """Test case for things_thing_id_images_image_id_delete

        Delete an image from a thing
        """
        pass

    def test_things_thing_id_images_image_id_get(self) -> None:
        """Test case for things_thing_id_images_image_id_get

        Get image(s) by thing
        """
        pass

    def test_things_thing_id_images_image_id_patch(self) -> None:
        """Test case for things_thing_id_images_image_id_patch

        Update an existing image
        """
        pass

    def test_things_thing_id_likes_delete(self) -> None:
        """Test case for things_thing_id_likes_delete

        Delete a like
        """
        pass

    def test_things_thing_id_likes_get(self) -> None:
        """Test case for things_thing_id_likes_get

        Get users who liked this thing
        """
        pass

    def test_things_thing_id_likes_post(self) -> None:
        """Test case for things_thing_id_likes_post

        Like a thing
        """
        pass

    def test_things_thing_id_patch(self) -> None:
        """Test case for things_thing_id_patch

        Update an existing thing
        """
        pass

    def test_things_thing_id_prints_get(self) -> None:
        """Test case for things_thing_id_prints_get

        Get a list of prints associated with a thing
        """
        pass

    def test_things_thing_id_publish_post(self) -> None:
        """Test case for things_thing_id_publish_post

        Publish a thing
        """
        pass

    def test_things_thing_id_root_comments_get(self) -> None:
        """Test case for things_thing_id_root_comments_get

        Get an unthreaded paginated list of root comment objects
        """
        pass

    def test_things_thing_id_tags_get(self) -> None:
        """Test case for things_thing_id_tags_get

        Get tags on this thing
        """
        pass

    def test_things_thing_id_threaded_comments_get(self) -> None:
        """Test case for things_thing_id_threaded_comments_get

        Get all comments for this thing in a quick pre-threaded view
        """
        pass

    def test_things_thing_id_toggle_watch_post(self) -> None:
        """Test case for things_thing_id_toggle_watch_post

        Watch/unwatch a Thing
        """
        pass


if __name__ == '__main__':
    unittest.main()
