# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.printers0_brands_get200_response_inner import Printers0BrandsGet200ResponseInner

class TestPrinters0BrandsGet200ResponseInner(unittest.TestCase):
    """Printers0BrandsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Printers0BrandsGet200ResponseInner:
        """Test Printers0BrandsGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Printers0BrandsGet200ResponseInner`
        """
        model = Printers0BrandsGet200ResponseInner()
        if include_optional:
            return Printers0BrandsGet200ResponseInner(
                name = 'Ultimaker'
            )
        else:
            return Printers0BrandsGet200ResponseInner(
        )
        """

    def testPrinters0BrandsGet200ResponseInner(self):
        """Test Printers0BrandsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
