# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.collection_api import CollectionApi


class TestCollectionApi(unittest.TestCase):
    """CollectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectionApi()

    def tearDown(self) -> None:
        pass

    def test_collections_collection_id_delete(self) -> None:
        """Test case for collections_collection_id_delete

        Delete a collection
        """
        pass

    def test_collections_collection_id_get(self) -> None:
        """Test case for collections_collection_id_get

        Get a collection by id
        """
        pass

    def test_collections_collection_id_like_post(self) -> None:
        """Test case for collections_collection_id_like_post

        Like/unlike Collection
        """
        pass

    def test_collections_collection_id_move_thing_id_post(self) -> None:
        """Test case for collections_collection_id_move_thing_id_post

        Move a thing between collections
        """
        pass

    def test_collections_collection_id_patch(self) -> None:
        """Test case for collections_collection_id_patch

        Update a collection
        """
        pass

    def test_collections_collection_id_thing_thing_id_delete(self) -> None:
        """Test case for collections_collection_id_thing_thing_id_delete

        Removes a thing from a collection
        """
        pass

    def test_collections_collection_id_thing_thing_id_post(self) -> None:
        """Test case for collections_collection_id_thing_thing_id_post

        Add a thing to a collection
        """
        pass

    def test_collections_collection_id_things_get(self) -> None:
        """Test case for collections_collection_id_things_get

        Get Things in a collection
        """
        pass

    def test_collections_collection_id_watch_post(self) -> None:
        """Test case for collections_collection_id_watch_post

        Watch/unwatch Collection
        """
        pass

    def test_collections_get(self) -> None:
        """Test case for collections_get

        Get list of the latest collections
        """
        pass

    def test_collections_post(self) -> None:
        """Test case for collections_post

        Create a new collection
        """
        pass

    def test_collections_thing_id_by_thing_id_get(self) -> None:
        """Test case for collections_thing_id_by_thing_id_get

        Get a collection by id
        """
        pass


if __name__ == '__main__':
    unittest.main()
