# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.program_api import ProgramApi


class TestProgramApi(unittest.TestCase):
    """ProgramApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProgramApi()

    def tearDown(self) -> None:
        pass

    def test_programs0_all_get(self) -> None:
        """Test case for programs0_all_get

        Get a list of programs
        """
        pass


if __name__ == '__main__':
    unittest.main()
