# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.member_schema import MemberSchema

class TestMemberSchema(unittest.TestCase):
    """MemberSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MemberSchema:
        """Test MemberSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MemberSchema`
        """
        model = MemberSchema()
        if include_optional:
            return MemberSchema(
                id = 56,
                name = '',
                first_name = '',
                last_name = '',
                url = '',
                public_url = '',
                thumbnail = '',
                count_of_followers = 56,
                count_of_following = 56,
                count_of_designs = 56,
                accepts_tips = True,
                is_following = True,
                location = '',
                cover = '',
                is_admin = True
            )
        else:
            return MemberSchema(
        )
        """

    def testMemberSchema(self):
        """Test MemberSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
