# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subscriptions0_dashboard_sources_get200_response_value_inner import Subscriptions0DashboardSourcesGet200ResponseValueInner

class TestSubscriptions0DashboardSourcesGet200ResponseValueInner(unittest.TestCase):
    """Subscriptions0DashboardSourcesGet200ResponseValueInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Subscriptions0DashboardSourcesGet200ResponseValueInner:
        """Test Subscriptions0DashboardSourcesGet200ResponseValueInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Subscriptions0DashboardSourcesGet200ResponseValueInner`
        """
        model = Subscriptions0DashboardSourcesGet200ResponseValueInner()
        if include_optional:
            return Subscriptions0DashboardSourcesGet200ResponseValueInner(
                name = '',
                image_url = '',
                target_url = '',
                target_type = '',
                target_id = 1
            )
        else:
            return Subscriptions0DashboardSourcesGet200ResponseValueInner(
        )
        """

    def testSubscriptions0DashboardSourcesGet200ResponseValueInner(self):
        """Test Subscriptions0DashboardSourcesGet200ResponseValueInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
