# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.sitewidenotification_api import SitewidenotificationApi


class TestSitewidenotificationApi(unittest.TestCase):
    """SitewidenotificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SitewidenotificationApi()

    def tearDown(self) -> None:
        pass

    def test_sitewidenotification_get(self) -> None:
        """Test case for sitewidenotification_get

        Get a sitewidenotification
        """
        pass

    def test_sitewidenotification_id_get(self) -> None:
        """Test case for sitewidenotification_id_get

        Get a sitewidenotification by id
        """
        pass


if __name__ == '__main__':
    unittest.main()
