# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.things_post404_response import ThingsPost404Response

class TestThingsPost404Response(unittest.TestCase):
    """ThingsPost404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThingsPost404Response:
        """Test ThingsPost404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThingsPost404Response`
        """
        model = ThingsPost404Response()
        if include_optional:
            return ThingsPost404Response(
                error = 'Not Found'
            )
        else:
            return ThingsPost404Response(
        )
        """

    def testThingsPost404Response(self):
        """Test ThingsPost404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
