# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.make_api import MakeApi


class TestMakeApi(unittest.TestCase):
    """MakeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MakeApi()

    def tearDown(self) -> None:
        pass

    def test_copies_copy_id_comments_get(self) -> None:
        """Test case for copies_copy_id_comments_get

        Get an unthreaded paginated list of comment objects.
        """
        pass

    def test_copies_copy_id_comments_post(self) -> None:
        """Test case for copies_copy_id_comments_post

        Post a comment
        """
        pass

    def test_copies_copy_id_delete(self) -> None:
        """Test case for copies_copy_id_delete

        Softdelete copy by id
        """
        pass

    def test_copies_copy_id_get(self) -> None:
        """Test case for copies_copy_id_get

        Get make (copy) by id
        """
        pass

    def test_copies_copy_id_images_get(self) -> None:
        """Test case for copies_copy_id_images_get

        Get images for a copy
        """
        pass

    def test_copies_copy_id_images_image_id_delete(self) -> None:
        """Test case for copies_copy_id_images_image_id_delete

        Delete an image from a copy
        """
        pass

    def test_copies_copy_id_images_image_id_patch(self) -> None:
        """Test case for copies_copy_id_images_image_id_patch

        Update an existing image
        """
        pass

    def test_copies_copy_id_images_post(self) -> None:
        """Test case for copies_copy_id_images_post

        Upload image to a copy
        """
        pass

    def test_copies_copy_id_likes_delete(self) -> None:
        """Test case for copies_copy_id_likes_delete

        Delete a like
        """
        pass

    def test_copies_copy_id_likes_post(self) -> None:
        """Test case for copies_copy_id_likes_post

        Like a copy
        """
        pass

    def test_copies_copy_id_patch(self) -> None:
        """Test case for copies_copy_id_patch

        Update an existing copy
        """
        pass

    def test_copies_copy_id_restore_post(self) -> None:
        """Test case for copies_copy_id_restore_post

        Restore a previously soft-deleted make
        """
        pass

    def test_copies_copy_id_root_comments_get(self) -> None:
        """Test case for copies_copy_id_root_comments_get

        Get an unthreaded paginated list of root comment objects
        """
        pass

    def test_copies_copy_id_threaded_comments_get(self) -> None:
        """Test case for copies_copy_id_threaded_comments_get

        Get all comments for this copy in a quick pre-threaded view.
        """
        pass

    def test_copies_copy_id_toggle_watch_post(self) -> None:
        """Test case for copies_copy_id_toggle_watch_post

        Watch/unwatch a Make
        """
        pass

    def test_copies_get(self) -> None:
        """Test case for copies_get

        Get the list of latest makes (copies).
        """
        pass

    def test_copiesreturncomplete_get(self) -> None:
        """Test case for copiesreturncomplete_get

        Get the list of latest makes (copies). The return complete ensures that the full thinginfo and image info is returned
        """
        pass


if __name__ == '__main__':
    unittest.main()
