# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.email_post_request import EmailPostRequest

class TestEmailPostRequest(unittest.TestCase):
    """EmailPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailPostRequest:
        """Test EmailPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailPostRequest`
        """
        model = EmailPostRequest()
        if include_optional:
            return EmailPostRequest(
                client_id = '615fc4464de0c742cafb',
                email_type = 'welcome',
                site = 'tv',
                user_id = 2,
                forgot_email = 'test@gmail.com'
            )
        else:
            return EmailPostRequest(
                email_type = 'welcome',
                site = 'tv',
                user_id = 2,
        )
        """

    def testEmailPostRequest(self):
        """Test EmailPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
