# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.things_post_request import ThingsPostRequest

class TestThingsPostRequest(unittest.TestCase):
    """ThingsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThingsPostRequest:
        """Test ThingsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThingsPostRequest`
        """
        model = ThingsPostRequest()
        if include_optional:
            return ThingsPostRequest(
                name = 'Test thing',
                license = 'cc',
                category = 'Other',
                description = 'Some kind of description about the thing that you are posting',
                instructions = 'This is an instruction!',
                is_wip = True,
                tags = [test, tag],
                ancestors = [2000],
                is_remix = False
            )
        else:
            return ThingsPostRequest(
                name = 'Test thing',
                license = 'cc',
                category = 'Other',
        )
        """

    def testThingsPostRequest(self):
        """Test ThingsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
