# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.changelog_schema_highlights_inner import ChangelogSchemaHighlightsInner
from typing import Optional, Set
from typing_extensions import Self

class ChangelogSchema(BaseModel):
    """
    ChangelogSchema
    """ # noqa: E501
    version: Optional[StrictStr] = None
    data: Optional[StrictStr] = None
    highlights: Optional[List[ChangelogSchemaHighlightsInner]] = None
    features: Optional[List[StrictStr]] = None
    bugfixes: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["version", "data", "highlights", "features", "bugfixes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChangelogSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in highlights (list)
        _items = []
        if self.highlights:
            for _item_highlights in self.highlights:
                if _item_highlights:
                    _items.append(_item_highlights.to_dict())
            _dict['highlights'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChangelogSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "data": obj.get("data"),
            "highlights": [ChangelogSchemaHighlightsInner.from_dict(_item) for _item in obj["highlights"]] if obj.get("highlights") is not None else None,
            "features": obj.get("features"),
            "bugfixes": obj.get("bugfixes")
        })
        return _obj


