# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GrouptopicsGrouptopicIdUpdatePostRequest(BaseModel):
    """
    GrouptopicsGrouptopicIdUpdatePostRequest
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Set the name of the topic")
    body: Optional[StrictStr] = Field(default=None, description="Set the body of the topic")
    tags: Optional[List[StrictStr]] = Field(default=None, description="Set the category of the thing. Uses full category name (eg. \"3D Printer Parts\")")
    filenames: Optional[List[StrictStr]] = Field(default=None, description="Array of names of the files")
    files: Optional[List[StrictStr]] = Field(default=None, description="Array of files")
    attachments: Optional[List[StrictStr]] = Field(default=None, description="Array of atachments ids to update")
    __properties: ClassVar[List[str]] = ["name", "body", "tags", "filenames", "files", "attachments"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GrouptopicsGrouptopicIdUpdatePostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GrouptopicsGrouptopicIdUpdatePostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "body": obj.get("body"),
            "tags": obj.get("tags"),
            "filenames": obj.get("filenames"),
            "files": obj.get("files"),
            "attachments": obj.get("attachments")
        })
        return _obj


