# coding: utf-8

"""
    API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UsersUsernameStatsByDayStartDateEndDateGet200ResponseInner(BaseModel):
    """
    UsersUsernameStatsByDayStartDateEndDateGet200ResponseInner
    """ # noqa: E501
    day: Optional[StrictStr] = None
    user_id: Optional[StrictInt] = None
    views: Optional[StrictInt] = None
    downloads: Optional[StrictInt] = None
    likes: Optional[StrictInt] = None
    collects: Optional[StrictInt] = None
    watches: Optional[StrictInt] = None
    comments: Optional[StrictInt] = None
    makes: Optional[StrictInt] = None
    derivatives: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["day", "user_id", "views", "downloads", "likes", "collects", "watches", "comments", "makes", "derivatives"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsersUsernameStatsByDayStartDateEndDateGet200ResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsersUsernameStatsByDayStartDateEndDateGet200ResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "day": obj.get("day"),
            "user_id": obj.get("user_id"),
            "views": obj.get("views"),
            "downloads": obj.get("downloads"),
            "likes": obj.get("likes"),
            "collects": obj.get("collects"),
            "watches": obj.get("watches"),
            "comments": obj.get("comments"),
            "makes": obj.get("makes"),
            "derivatives": obj.get("derivatives")
        })
        return _obj


